Repository inworld-ai/inworld-nodejs-sdk, pull requests merged in 2024-09, with the labels that each got.

#271 [Automated build] Update Protobuf files
  proto/ai/inworld/packets/packets_pb.d.ts
  proto/ai/inworld/packets/packets_pb.js
Labels: automated-protobuf-update

#276 fix: Add user to scene automatically in case of one-to-one conversation
  CHANGELOG.md
  src/common/data_structures.ts
  src/factories/event.ts
  src/index.ts
  src/services/conversation.service.ts
  src/services/inworld_connection.service.ts
Labels: bug

#258 Examples for 1.15
  examples/js/cli/auto_reconnect.js
  examples/js/cli/manual_reconnect.js
  examples/js/cli/package.json
  examples/js/cli/yarn.lock
  examples/js/generate_token/package.json
  examples/js/generate_token/yarn.lock
  examples/js/say_hello/package.json
  examples/js/say_hello/yarn.lock
  examples/js/upload_local_audio_file/package.json
  examples/js/upload_local_audio_file/yarn.lock
  examples/ts/cli/auto_reconnect.ts
  examples/ts/cli/components/client.ts
  examples/ts/cli/components/types.ts
  examples/ts/cli/helpers.ts
  examples/ts/cli/manual_reconnect.ts
  examples/ts/cli/map.ts
  examples/ts/cli/package.json
  examples/ts/cli/yarn.lock
  examples/ts/discord_bot/package.json
  examples/ts/discord_bot/yarn.lock
  examples/ts/generate_token/package.json
  examples/ts/generate_token/yarn.lock
  examples/ts/say_hello/package.json
  examples/ts/say_hello/yarn.lock
  examples/ts/upload_local_audio_file/package.json
  examples/ts/upload_local_audio_file/yarn.lock
Labels: example
